language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install portalocker
  - python setup.py install
# command to run tests
script: python cotimelog/tests.py